### ISSUE TITLE
Error in .jar

### ISSUE THREAD

**Issue by Jallepro10** [LBuddyBoy/Xenlan-Abilities#1]
How can I convert the files to a .jar without error, since when converting the files I get this error.
I have Spigot 1.7.10 and the error that I get is this:

[14:47:04] [Server thread/ERROR]: Could not load 'plugins\XenlanAbilities.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_301]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_301]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_301]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_301]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_301]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 5 more

**Comment by hola4885** [comment]
This resource is no longer active for 4 years
